export const ROUTES = {
  HOME: "/",
  LOGIN: "/login",
  REGISTER: "/register",
  FORGOT_PASSWORD: "/forgot-password",
  ABOUT: "/#about",
  CONTACT: "/#contact",
  DASHBOARD: {
    OVERVIEW: "/dashboard",
    CROP_ADVISOR: "/dashboard/crop-advisor",
    POST_HARVEST: "/dashboard/post-harvest",
    DISEASE_DETECTION: "/dashboard/disease-detection",
    MARKET_PRICES: "/dashboard/market-prices",
    WEATHER: "/dashboard/weather",
    HISTORY: "/dashboard/history",
    REPORTS: "/dashboard/reports",
    SETTINGS: "/dashboard/settings",
    IRRIGATION: "/dashboard/irrigation",
    PROFILE: "/dashboard/profile",
    ADMIN: "/dashboard/admin",
  },
  SERVICES: {
    TRACTOR_RENT: "/services/tractor-rent",
    HARVESTER_RENT: "/services/harvester-rent",
    STORAGE_RENT: "/services/storage-rent",
    COLD_STORAGE: "/services/cold-storage",
    GOVERNMENT_SUBSIDIES: "/services/government-subsidies",
    CENTRAL_SCHEMES: "/services/central-schemes",
    NEAREST_MANDI: "/services/nearest-mandi",
    LIVE_MANDI_PRICES: "/services/live-mandi-prices",
  },
};