import * as React from "react";
import { Sparkles, ShieldCheck, CheckCircle2 } from "lucide-react";

export function AIFeatures() {
  return (
    <section className="py-16 bg-slate-50">
      <div className="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8 flex flex-col md:flex-row items-center gap-12">
        <div className="space-y-6 flex-1">
          <span className="inline-flex items-center gap-1.5 rounded-full bg-emerald-100 px-3 py-1 text-xs font-bold text-emerald-800">
            <Sparkles className="h-4 w-4 text-emerald-600" /> Powered by Deep AgriTech Machine Learning
          </span>
          <h2 className="text-3xl font-black text-slate-900 leading-tight">
            Confidence Indicators & Explainable Recommendations
          </h2>
          <p className="text-sm text-slate-600 leading-relaxed">
            Every advisory generated by KrishiMitra includes explicit confidence indicators (High, Medium, Low) along with plain-language explanations of why a specific action is recommended.
          </p>
          <ul className="space-y-3 text-xs font-bold text-slate-800">
            <li className="flex items-center gap-2">
              <CheckCircle2 className="h-4 w-4 text-emerald-600" /> Top 3 ranked recommendations tailored to soil & PIN code
            </li>
            <li className="flex items-center gap-2">
              <CheckCircle2 className="h-4 w-4 text-emerald-600" /> 7-Day Day-by-Day Irrigation & Spraying Timeline
            </li>
            <li className="flex items-center gap-2">
              <CheckCircle2 className="h-4 w-4 text-emerald-600" /> Real-time APMC Mandi price & freight cost calculator
            </li>
          </ul>
        </div>
        <div className="flex-1 rounded-3xl border border-slate-200 bg-white p-6 shadow-lg space-y-4">
          <div className="flex items-center justify-between border-b border-slate-100 pb-3">
            <h4 className="font-bold text-slate-900 text-sm">Sample Ranked Advisory</h4>
            <span className="rounded-full bg-emerald-50 px-2.5 py-1 text-xs font-bold text-emerald-700 border border-emerald-200">
              High Confidence (94%)
            </span>
          </div>
          <p className="text-xs text-slate-600">
            "Apply 25 kg/acre Urea top-dressing tomorrow morning following micro-sprinkler irrigation to prevent nitrogen leaching."
          </p>
        </div>
      </div>
    </section>
  );
}